In [10]:
import numpy
import sys
sys.path.append('../../main/regression/')
import scipy.io
import riskExperiment2

#### To Be Specified
filename = 'UG_n=100000_d=500.mat' 

# load data
dataname = filename[0:2]
dataDict = scipy.io.loadmat(filename)
matX = dataDict['matX']
vecW = dataDict['vecW']
print(matX.shape)
matU, vecS, matV = numpy.linalg.svd(matX, full_matrices=False)
vecLev = numpy.sum(matU ** 2, axis=1)
print('max leverge score is ' + str(max(vecLev)))



(100000, 500)
max leverge score is 0.00680884447576


In [11]:
# Parameters Fixed for All the Experiments
vecGamma = [0, 1e-12, 1e-11, 1e-10, 1e-9, 1e-8, 3e-8, 1e-7, 2e-7, 5e-7, 1e-6, 3e-6, 1e-5, 1e-4, 1e-3, 1e-2]
#sketchSizes = [1000, 1100, 1300, 1500, 1700, 2000, 2400, 2800, 3300, 3800, 4400, 5000, 5700, 6400, 7200]

#vecGamma = [1e-6]
sketchSizes = [5000]



In [12]:

##### Parameters to Be Specified
xi = 0.1 # 0.01, 0.02, 0.05, 0.1, 0.2

# Name the output file by the data name + xi value
outputFileName = dataname + '2_BiasVar_xi=' + str(xi) + '.mat'
print(outputFileName)

print(sketchSizes)
resultDict = riskExperiment2.biasVariance(matX, vecW, xi, vecGamma, sketchSizes, matU, vecS, matV, vecLev)
scipy.io.savemat(outputFileName, resultDict)




UG2_BiasVar_xi=0.1.mat
[5000]
Testing Optimal Ridge Regression
[[  5.00000000e-05]
 [  4.99998992e-05]
 [  4.99989919e-05]
 [  4.99899260e-05]
 [  4.98999398e-05]
 [  4.90626340e-05]
 [  4.75358944e-05]
 [  4.43789356e-05]
 [  4.28091811e-05]
 [  4.58460187e-05]
 [  5.97713337e-05]
 [  1.32290519e-04]
 [  3.18721084e-04]
 [  6.55841356e-04]
 [  7.27243387e-04]
 [  7.35160765e-04]]
Testing Uniform Sampling
Testing Leverage Score Sampling
Testing Leverage Score Sampling
Testing Mixed Sampling
Testing Gaussian Projection
Testing SRFT
Testing Count Sketch


In [13]:
print(resultDict['biasRR'])

print(resultDict['biasUniform'])
print(resultDict['biasLev'])
print(resultDict['biasMix'])
print(resultDict['biasGauss'])
print(resultDict['biasSRFT'])
print(resultDict['biasCount'])


[[  0.00000000e+00]
 [  1.92561305e-16]
 [  1.92550509e-14]
 [  1.92442628e-12]
 [  1.91371875e-10]
 [  1.81408895e-08]
 [  1.46855825e-07]
 [  1.23211278e-06]
 [  3.74380732e-06]
 [  1.41893325e-05]
 [  3.50309774e-05]
 [  1.19147572e-04]
 [  3.14722073e-04]
 [  6.55744230e-04]
 [  7.27242289e-04]
 [  7.35160754e-04]]
[[  9.95148352e-05]
 [  9.95144772e-05]
 [  9.95112551e-05]
 [  9.94790555e-05]
 [  9.91591084e-05]
 [  9.61483154e-05]
 [  9.04420358e-05]
 [  7.66600391e-05]
 [  6.50682987e-05]
 [  5.15891515e-05]
 [  5.38748195e-05]
 [  1.19119444e-04]
 [  3.12600085e-04]
 [  6.55704340e-04]
 [  7.27241948e-04]
 [  7.35160751e-04]]
[[  1.03514273e-04]
 [  1.03513884e-04]
 [  1.03510382e-04]
 [  1.03475394e-04]
 [  1.03127697e-04]
 [  9.98526941e-05]
 [  9.36335883e-05]
 [  7.85894650e-05]
 [  6.59377538e-05]
 [  5.09824625e-05]
 [  5.23730145e-05]
 [  1.17427969e-04]
 [  3.12093732e-04]
 [  6.55707780e-04]
 [  7.27242038e-04]
 [  7.35160752e-04]]
[[  1.03781999e-04]
 [  1.03781610e-0

In [14]:
print(resultDict['varRR'])

print(resultDict['varUniform'])
print(resultDict['varLev'])
print(resultDict['varMix'])
print(resultDict['varGauss'])
print(resultDict['varSRFT'])
print(resultDict['varCount'])

[[  5.00000000e-05]
 [  4.99998992e-05]
 [  4.99989919e-05]
 [  4.99899241e-05]
 [  4.98997485e-05]
 [  4.90444931e-05]
 [  4.73890386e-05]
 [  4.31468228e-05]
 [  3.90653738e-05]
 [  3.16566862e-05]
 [  2.47403562e-05]
 [  1.31429474e-05]
 [  3.99901133e-06]
 [  9.71260820e-08]
 [  1.09812716e-09]
 [  1.11229202e-11]]
[[  6.76310795e-05]
 [  6.76308962e-05]
 [  6.76292473e-05]
 [  6.76127690e-05]
 [  6.74490597e-05]
 [  6.59103804e-05]
 [  6.29973561e-05]
 [  5.58519166e-05]
 [  4.93281545e-05]
 [  3.82331841e-05]
 [  2.86727818e-05]
 [  1.42201101e-05]
 [  4.09758184e-06]
 [  9.71824188e-08]
 [  1.09813019e-09]
 [  1.11229162e-11]]
[[  6.75507677e-05]
 [  6.75505855e-05]
 [  6.75489455e-05]
 [  6.75325564e-05]
 [  6.73697292e-05]
 [  6.58389370e-05]
 [  6.29389973e-05]
 [  5.58176371e-05]
 [  4.93093907e-05]
 [  3.82326595e-05]
 [  2.86810136e-05]
 [  1.42292269e-05]
 [  4.10024157e-06]
 [  9.71977301e-08]
 [  1.09814981e-09]
 [  1.11229363e-11]]
[[  6.75899725e-05]
 [  6.75897895e-0