In [1]:
import numpy
import sys
sys.path.append('../../main/regression/')
import scipy.io

#### To Be Specified
filename = 'NB_n=100000_d=500.mat' 

# load data
dataname = filename[0:2]
dataDict = scipy.io.loadmat(filename)
matX = dataDict['matX']
vecW = dataDict['vecW']
print(matX.shape)
matU, vecS, matV = numpy.linalg.svd(matX, full_matrices=False)
vecLev = numpy.sum(matU ** 2, axis=1)
print(max(vecLev))




(100000, 500)
0.996301643078


In [2]:
import biasVarExperiment




# Parameters Fixed for All the Experiments
vecGamma = [0, 1e-12, 1e-11, 1e-10, 1e-9, 1e-8, 3e-8, 1e-7, 2e-7, 5e-7, 1e-6, 3e-6, 1e-5, 1e-4, 1e-3, 1e-2]
sketchSizes = [1500, 1700, 2000, 2400, 2800, 3300, 3800, 4400, 5000, 5700, 6400, 7200]

#vecGamma = [1e-12, 1e-8]
#sketchSizes = [2000, 5000]




In [3]:

##### Parameters to Be Specified
xi = 0.01 # 0.01, 0.02, 0.05, 0.1, 0.2

# Name the output file by the data name + xi value
outputFileName = dataname + '_BiasVar_xi=' + str(xi) + '.mat'
print(outputFileName)


resultDict = biasVarExperiment.biasVariance(matX, vecW, xi, vecGamma, sketchSizes, matU, vecS, matV, vecLev)
scipy.io.savemat(outputFileName, resultDict)


NB_BiasVar_xi=0.01.mat
Testing Optimal Ridge Regression
[[  5.00000000e-07]
 [  2.73530697e-07]
 [  2.32023779e-07]
 [  1.91146725e-07]
 [  1.56195596e-07]
 [  1.80870688e-07]
 [  2.96890783e-07]
 [  7.57448205e-07]
 [  1.44101887e-06]
 [  3.42409977e-06]
 [  6.39838844e-06]
 [  1.58347370e-05]
 [  3.50672843e-05]
 [  6.79383151e-05]
 [  7.49115806e-05]
 [  7.56859626e-05]]
Testing SRFT
[[  4.97412420e-05   4.14938389e-05   3.31808224e-05   2.61758747e-05
    2.16374020e-05   1.77770824e-05   1.50698204e-05   1.27590772e-05
    1.10603271e-05   9.56642876e-06   8.43020549e-06   7.42523702e-06]
 [  2.18522326e-05   1.88599932e-05   1.56233630e-05   1.27067337e-05
    1.07138421e-05   8.95739455e-06   7.69215948e-06   6.57896490e-06
    5.74868872e-06   5.00808520e-06   4.43919775e-06   3.92793411e-06]
 [  1.79420102e-05   1.55514067e-05   1.29479062e-05   1.05727741e-05
    8.93821883e-06   7.49517954e-06   6.44928347e-06   5.52620452e-06
    4.83511705e-06   4.21603295e-06   3.74093603

In [4]:

##### Parameters to Be Specified
xi = 0.02 # 0.01, 0.02, 0.05, 0.1, 0.2

# Name the output file by the data name + xi value
outputFileName = dataname + '_BiasVar_xi=' + str(xi) + '.mat'
print(outputFileName)


resultDict = biasVarExperiment.biasVariance(matX, vecW, xi, vecGamma, sketchSizes, matU, vecS, matV, vecLev)
scipy.io.savemat(outputFileName, resultDict)

NB_BiasVar_xi=0.02.mat
Testing Optimal Ridge Regression
[[  2.00000000e-06]
 [  1.09410247e-06]
 [  9.27845648e-07]
 [  7.62219542e-07]
 [  6.02527897e-07]
 [  5.02547758e-07]
 [  5.59257133e-07]
 [  9.55316191e-07]
 [  1.60236461e-06]
 [  3.53881004e-06]
 [  6.48029098e-06]
 [  1.58733963e-05]
 [  3.50781271e-05]
 [  6.79385661e-05]
 [  7.49115834e-05]
 [  7.56859626e-05]]
Testing SRFT
[[  1.99163727e-04   1.66151919e-04   1.32702218e-04   1.04735169e-04
    8.65340300e-05   7.11174534e-05   6.02806624e-05   5.10311775e-05
    4.42069193e-05   3.82839705e-05   3.37283145e-05   2.97143949e-05]
 [  8.75263532e-05   7.54592352e-05   6.24795800e-05   5.08457265e-05
    4.28706182e-05   3.58302434e-05   3.07658190e-05   2.63160401e-05
    2.29745746e-05   2.00481263e-05   1.77525407e-05   1.57186914e-05]
 [  7.18616256e-05   6.22206196e-05   5.18081582e-05   4.23327317e-05
    3.57813714e-05   2.99865684e-05   2.57958104e-05   2.21022271e-05
    1.93166989e-05   1.68800866e-05   1.49559375

In [5]:

##### Parameters to Be Specified
xi = 0.05 # 0.01, 0.02, 0.05, 0.1, 0.2

# Name the output file by the data name + xi value
outputFileName = dataname + '_BiasVar_xi=' + str(xi) + '.mat'
print(outputFileName)


resultDict = biasVarExperiment.biasVariance(matX, vecW, xi, vecGamma, sketchSizes, matU, vecS, matV, vecLev)
scipy.io.savemat(outputFileName, resultDict)

NB_BiasVar_xi=0.05.mat
Testing Optimal Ridge Regression
[[  1.25000000e-05]
 [  6.83810489e-06]
 [  5.79859873e-06]
 [  4.75972926e-06]
 [  3.72685400e-06]
 [  2.75428725e-06]
 [  2.39582158e-06]
 [  2.34039209e-06]
 [  2.73178476e-06]
 [  4.34178198e-06]
 [  7.05360879e-06]
 [  1.61440117e-05]
 [  3.51540269e-05]
 [  6.79403235e-05]
 [  7.49116032e-05]
 [  7.56859628e-05]]
Testing SRFT
[[  1.24619658e-03   1.03748588e-03   8.30015729e-04   6.54955954e-04
    5.41411362e-04   4.44412072e-04   3.76845113e-04   3.19211561e-04
    2.76492524e-04   2.39199598e-04   2.10806686e-04   1.85770444e-04]
 [  5.47398271e-04   4.71496662e-04   3.90163005e-04   3.17987992e-04
    2.68078936e-04   2.23873783e-04   1.92229207e-04   1.64544723e-04
    1.43750648e-04   1.25254578e-04   1.10978371e-04   9.82447273e-05]
 [  4.49336429e-04   3.88774267e-04   3.23269754e-04   2.64733438e-04
    2.23714734e-04   1.87328327e-04   1.61180803e-04   1.38194404e-04
    1.20888928e-04   1.05451671e-04   9.35087522

In [6]:

##### Parameters to Be Specified
xi = 0.1 # 0.01, 0.02, 0.05, 0.1, 0.2

# Name the output file by the data name + xi value
outputFileName = dataname + '_BiasVar_xi=' + str(xi) + '.mat'
print(outputFileName)


resultDict = biasVarExperiment.biasVariance(matX, vecW, xi, vecGamma, sketchSizes, matU, vecS, matV, vecLev)
scipy.io.savemat(outputFileName, resultDict)

NB_BiasVar_xi=0.1.mat
Testing Optimal Ridge Regression
[[  5.00000000e-05]
 [  2.73523992e-05]
 [  2.31941454e-05]
 [  1.90365497e-05]
 [  1.48851615e-05]
 [  1.07962140e-05]
 [  8.95498032e-06]
 [  7.28709173e-06]
 [  6.76542817e-06]
 [  7.20953889e-06]
 [  9.10117241e-06]
 [  1.71104954e-05]
 [  3.54250978e-05]
 [  6.79465996e-05]
 [  7.49116737e-05]
 [  7.56859636e-05]]
Testing SRFT
[[  4.97477049e-03   4.14973683e-03   3.32031682e-03   2.61907054e-03
    2.16341654e-03   1.77752356e-03   1.50662945e-03   1.27590108e-03
    1.10546990e-03   9.56962340e-04   8.43391985e-04   7.42891350e-04]
 [  2.18827719e-03   1.88546814e-03   1.56285672e-03   1.27107073e-03
    1.07124327e-03   8.95749230e-04   7.68826478e-04   6.58128230e-04
    5.74542742e-04   5.01297310e-04   4.43994616e-04   3.92948182e-04]
 [  1.79649306e-03   1.55487981e-03   1.29488171e-03   1.05785197e-03
    8.94080264e-04   7.49626259e-04   6.44570679e-04   5.52824176e-04
    4.83165456e-04   4.22079260e-04   3.74110304e

In [7]:

##### Parameters to Be Specified
xi = 0.2 # 0.01, 0.02, 0.05, 0.1, 0.2

# Name the output file by the data name + xi value
outputFileName = dataname + '_BiasVar_xi=' + str(xi) + '.mat'
print(outputFileName)


resultDict = biasVarExperiment.biasVariance(matX, vecW, xi, vecGamma, sketchSizes, matU, vecS, matV, vecLev)
scipy.io.savemat(outputFileName, resultDict)

NB_BiasVar_xi=0.2.mat
Testing Optimal Ridge Regression
[[  2.00000000e-04]
 [  1.09409577e-04]
 [  9.27763323e-05]
 [  7.61438314e-05]
 [  5.95183916e-05]
 [  4.29639211e-05]
 [  3.51916153e-05]
 [  2.70738903e-05]
 [  2.29000018e-05]
 [  1.86805665e-05]
 [  1.72914269e-05]
 [  2.09764298e-05]
 [  3.65093812e-05]
 [  6.79717044e-05]
 [  7.49119560e-05]
 [  7.56859664e-05]]
Testing SRFT
[[  1.99124515e-02   1.66146590e-02   1.32715688e-02   1.04768605e-02
    8.65821157e-03   7.11092899e-03   6.03413529e-03   5.10566518e-03
    4.42308818e-03   3.82932013e-03   3.37332254e-03   2.97197372e-03]
 [  8.75299607e-03   7.54635331e-03   6.24787547e-03   5.08793412e-03
    4.28865277e-03   3.58107613e-03   3.08061817e-03   2.63180740e-03
    2.30014541e-03   2.00509029e-03   1.77671437e-03   1.57267438e-03]
 [  7.18512092e-03   6.22481879e-03   5.17741556e-03   4.23348596e-03
    3.57852892e-03   2.99677492e-03   2.58322112e-03   2.21082936e-03
    1.93440161e-03   1.68816452e-03   1.49689970e

In [8]:
print(resultDict['biasRR'] + resultDict['varRR'])
print(resultDict['biasUniform'] + resultDict['varUniform'])
print(resultDict['biasLev'] + resultDict['varLev'])
print(resultDict['biasMix'] + resultDict['varMix'])
print(resultDict['biasGauss'] + resultDict['varGauss'])
print(resultDict['biasCount'] + resultDict['varCount'])


[[  2.00000000e-04]
 [  1.09409577e-04]
 [  9.27763323e-05]
 [  7.61438314e-05]
 [  5.95183916e-05]
 [  4.29639211e-05]
 [  3.51916153e-05]
 [  2.70738903e-05]
 [  2.29000018e-05]
 [  1.86805665e-05]
 [  1.72914269e-05]
 [  2.09764298e-05]
 [  3.65093812e-05]
 [  6.79717044e-05]
 [  7.49119560e-05]
 [  7.56859664e-05]]
[[  1.41684908e-01   1.09328437e-01   8.19010670e-02   6.12261052e-02
    4.81598099e-02   3.62510181e-02   2.92495743e-02   2.34270635e-02
    1.83825938e-02   1.56011453e-02   1.36670807e-02   1.11090707e-02]
 [  4.38428573e-02   3.50862215e-02   2.81338344e-02   2.23263464e-02
    1.80921049e-02   1.40565915e-02   1.16454006e-02   9.60877220e-03
    7.54670070e-03   6.60510613e-03   5.84748953e-03   4.80451921e-03]
 [  3.34955324e-02   2.70776393e-02   2.18436360e-02   1.74564656e-02
    1.42573520e-02   1.11091778e-02   9.29253484e-03   7.67319415e-03
    6.05918006e-03   5.30709833e-03   4.71412970e-03   3.88058349e-03]
 [  2.40562539e-02   1.96674109e-02   1.595535

In [9]:

##### Parameters to Be Specified
xi = 0.5 # 0.01, 0.02, 0.05, 0.1, 0.2

# Name the output file by the data name + xi value
outputFileName = dataname + '_BiasVar_xi=' + str(xi) + '.mat'
print(outputFileName)


resultDict = biasVarExperiment.biasVariance(matX, vecW, xi, vecGamma, sketchSizes, matU, vecS, matV, vecLev)
scipy.io.savemat(outputFileName, resultDict)

NB_BiasVar_xi=0.5.mat
Testing Optimal Ridge Regression
[[  1.25000000e-03]
 [  6.83809818e-04]
 [  5.79851640e-04]
 [  4.75894803e-04]
 [  3.71951002e-04]
 [  2.68137871e-04]
 [  2.18848060e-04]
 [  1.65581480e-04]
 [  1.35842017e-04]
 [  9.89777600e-05]
 [  7.46232081e-05]
 [  4.80379711e-05]
 [  4.40993654e-05]
 [  6.81474380e-05]
 [  7.49139321e-05]
 [  7.56859864e-05]]
Testing SRFT
[[  1.24360447e-01   1.03562532e-01   8.29472698e-02   6.54834504e-02
    5.40836613e-02   4.44468473e-02   3.77085456e-02   3.18995583e-02
    2.76376755e-02   2.39207213e-02   2.10786000e-02   1.85748599e-02]
 [  5.46433272e-02   4.70739324e-02   3.90545614e-02   3.17963470e-02
    2.68035258e-02   2.23950961e-02   1.92430329e-02   1.64491574e-02
    1.43692574e-02   1.25229959e-02   1.10986094e-02   9.82361330e-03]
 [  4.48728778e-02   3.88155196e-02   3.23589197e-02   2.64516036e-02
    2.23711257e-02   1.87394234e-02   1.61359385e-02   1.38169002e-02
    1.20823051e-02   1.05414356e-02   9.35292987e