In [13]:
import numpy
import sys
sys.path.append('../../main/regression/')
import scipy.io

#### To Be Specified
filename = 'UB_n=100000_d=500.mat' 

# load data
dataname = filename[0:2]
dataDict = scipy.io.loadmat(filename)
matX = dataDict['matX']
vecW = dataDict['vecW']
print(matX.shape)
matU, vecS, matV = numpy.linalg.svd(matX, full_matrices=False)
vecLev = numpy.sum(matU ** 2, axis=1)
print(max(vecLev))




(100000, 500)
0.00654586469141


In [14]:
import biasVarExperiment




# Parameters Fixed for All the Experiments
vecGamma = [0, 1e-12, 1e-11, 1e-10, 3e-10, 1e-9, 3e-9, 1e-8, 2e-8, 5e-8, 1e-7, 2e-7, 5e-7, 1e-6, 2e-6, 5e-6, 1e-5, 3e-5, 1e-4, 1e-3, 1e-2]
sketchSizes = [5000] #[1500, 1700, 2000, 2400, 2800, 3300, 3800, 4400, 5000, 5700, 6400, 7200]

#vecGamma = [1e-12, 1e-8]
#sketchSizes = [2000, 5000]




In [15]:

##### Parameters to Be Specified
xi = 0.1 # 0.01, 0.02, 0.05, 0.1, 0.2

# Name the output file by the data name + xi value
outputFileName = dataname + '_BiasVar_xi=' + str(xi) + '.mat'
print(outputFileName)


resultDict = biasVarExperiment.biasVariance(matX, vecW, xi, vecGamma, sketchSizes, matU, vecS, matV, vecLev)
scipy.io.savemat(outputFileName, resultDict)


UB_BiasVar_xi=0.1.mat
Testing Optimal Ridge Regression
[[  5.00000000e-05]
 [  2.73524013e-05]
 [  2.31941511e-05]
 [  1.90364872e-05]
 [  1.70538661e-05]
 [  1.48845461e-05]
 [  1.29139895e-05]
 [  1.07844344e-05]
 [  9.59934130e-06]
 [  8.15855946e-06]
 [  7.27225962e-06]
 [  6.73680437e-06]
 [  7.08621894e-06]
 [  8.80849753e-06]
 [  1.25292283e-05]
 [  2.09982504e-05]
 [  2.90185997e-05]
 [  4.01735039e-05]
 [  4.68811022e-05]
 [  5.02152439e-05]
 [  5.05788873e-05]]
Testing SRFT
[[  1.10514475e-03]
 [  5.74671296e-04]
 [  4.83261789e-04]
 [  3.93352348e-04]
 [  3.51001237e-04]
 [  3.04963636e-04]
 [  2.63307789e-04]
 [  2.18077465e-04]
 [  1.92295589e-04]
 [  1.58643748e-04]
 [  1.33708771e-04]
 [  1.09571567e-04]
 [  7.99688294e-05]
 [  6.07551537e-05]
 [  4.61009781e-05]
 [  3.62566919e-05]
 [  3.58787069e-05]
 [  4.14984002e-05]
 [  4.70221524e-05]
 [  5.02146065e-05]
 [  5.05786553e-05]]
Testing Uniform Sampling
[[  1.10548425e-03]
 [  5.74765128e-04]
 [  4.83326473e-04]
 [  3